services:
  gateway:
    build:
      context: ../
      dockerfile: Docker/gateway/Dockerfile
    container_name: gateway
    privileged: true
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      internal-net:
        ipv4_address: 172.31.42.254

  target:
    build:
      context: ../
      dockerfile: Docker/target/Dockerfile
    container_name: target
    privileged: true
    tty: true
    stdin_open: true
    networks:
      internal-net:
        ipv4_address: 172.31.42.10

  source:
    build:
      context: ../
      dockerfile: Docker/source/Dockerfile
    container_name: source
    privileged: true
    sysctls:
      net.ipv4.ip_forward: "1"
    tty: true
    stdin_open: true
    networks:
      internal-net:
        ipv4_address: 172.31.42.100

networks:
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.42.0/24
          gateway: 172.31.42.1
